package orm;

import java.lang.reflect.Field;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import orm.annotations.*;

public class OrmManager {
    private Connection connection;

    public OrmManager(String dbName) {
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            this.connection = DriverManager.getConnection("jdbc:derby:" + dbName + ";create=true");
        } catch (Exception e) {
            throw new RuntimeException("Failed to connect to DB: " + e.getMessage(), e);
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public <T> void save(T obj) throws Exception {
    	EntityMetaData meta = new EntityMetaData(obj.getClass());
        Field idField = meta.getIdField();
        idField.setAccessible(true);
       boolean autoGenerated = idField.isAnnotationPresent(GeneratedValue.class);
        Object idValue = idField.get(obj);
    
        // *** NEW: If the object's ID is already set (nonzero), assume it’s already persisted and skip saving.
        if (autoGenerated && idValue != null && ((Integer)idValue) != 0) {
            return;
        }
    
       StringBuilder sql = new StringBuilder("INSERT INTO " + meta.getTableName() + " (");
        StringBuilder placeholders = new StringBuilder();
        List<Object> values = new ArrayList<>();
    
        // Only include the ID if it's NOT auto-generated
        if (!autoGenerated) {
           Column idColumn = idField.getAnnotation(Column.class);
            sql.append(idColumn.name());
            placeholders.append("?");
            values.add(idValue);
        }
        
        

        for (Field field : meta.getColumns()) {
            if (field.equals(idField)) continue;
            field.setAccessible(true);
            String columnName = "";
            Object fieldValue = null;
            if (field.isAnnotationPresent(Column.class)) {
                Column column = field.getAnnotation(Column.class);
                columnName = column.name();
                fieldValue = field.get(obj);
            } else if (field.isAnnotationPresent(JoinColumn.class)) {
                JoinColumn joinColumn = field.getAnnotation(JoinColumn.class);
                columnName = joinColumn.name();
                Object relatedObj = field.get(obj);
                if (relatedObj != null) {
                    fieldValue = relatedObj.getClass().getMethod("getId").invoke(relatedObj);
                }
            }
            if (sql.toString().endsWith("(")) {
                sql.append(columnName);
                placeholders.append("?");
            } else {
                sql.append(", ").append(columnName);
                placeholders.append(", ?");
            }
            values.add(fieldValue);
        }

        sql.append(") VALUES (").append(placeholders).append(")");

        if (autoGenerated) {
            try (PreparedStatement stmt = connection.prepareStatement(sql.toString(), Statement.RETURN_GENERATED_KEYS)) {
                for (int i = 0; i < values.size(); i++) {
                    stmt.setObject(i + 1, values.get(i));
                }
                stmt.executeUpdate();
                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        int generatedId = generatedKeys.getInt(1);
                        idField.set(obj, generatedId);
                    }
                }
            }
        } else {
            try (PreparedStatement stmt = connection.prepareStatement(sql.toString())) {
                for (int i = 0; i < values.size(); i++) {
                    stmt.setObject(i + 1, values.get(i));
                }
                stmt.executeUpdate();
            }
        }
    }
    
    public <T> T findById(Class<T> clazz, int id) throws Exception {
        EntityMetaData meta = new EntityMetaData(clazz);
        String sql = "SELECT * FROM " + meta.getTableName() + " WHERE id = ?";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setInt(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    T obj = clazz.getDeclaredConstructor().newInstance();
                    meta.populateFieldsFromResultSet(obj, rs, connection);
                    return obj;
                }
            }
        }
        return null;
    }


    public <T> T find(Class<T> clazz, Object id) throws Exception {
        EntityMetaData meta = new EntityMetaData(clazz);
        Field idField = meta.getIdField();
        Column idColumn = idField.getAnnotation(Column.class);
        String idColumnName = idColumn.name();

        String sql = "SELECT * FROM " + meta.getTableName() + " WHERE " + idColumnName + " = ?";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setObject(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    T obj = clazz.getDeclaredConstructor().newInstance();
                    idField.setAccessible(true);
                    idField.set(obj, rs.getObject(idColumn.name()));
                    for (Field field : meta.getColumns()) {
                        if (field.equals(idField)) continue;
                        field.setAccessible(true);
                        if (field.isAnnotationPresent(Column.class)) {
                            Column column = field.getAnnotation(Column.class);
                            field.set(obj, rs.getObject(column.name()));
                        } else if (field.isAnnotationPresent(JoinColumn.class)) {
                            JoinColumn joinColumn = field.getAnnotation(JoinColumn.class);
                            Object fk = rs.getObject(joinColumn.name());
                            if (fk != null) {
                                Object relatedObj = find(field.getType(), fk);
                                field.set(obj, relatedObj);
                            }
                        }
                    }
                    return obj;
                } else {
                    return null;
                }
            }
        }
    }

    public <T> List<T> findAll(Class<T> clazz) throws Exception {
        EntityMetaData meta = new EntityMetaData(clazz);
        List<T> results = new ArrayList<>();
        Field idField = meta.getIdField();

        String sql = "SELECT * FROM " + meta.getTableName();
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    T obj = clazz.getDeclaredConstructor().newInstance();
                    idField.setAccessible(true);
                    Column idColumn = idField.getAnnotation(Column.class);
                    Object idValue = rs.getObject(idColumn.name());
                    idField.set(obj, idValue);
                    for (Field field : meta.getColumns()) {
                        if (field.equals(idField)) continue;
                        field.setAccessible(true);
                        if (field.isAnnotationPresent(Column.class)) {
                            Column column = field.getAnnotation(Column.class);
                            field.set(obj, rs.getObject(column.name()));
                        } else if (field.isAnnotationPresent(JoinColumn.class)) {
                            JoinColumn joinColumn = field.getAnnotation(JoinColumn.class);
                            Object fk = rs.getObject(joinColumn.name());
                            if (fk != null) {
                                Object relatedObj = find(field.getType(), fk);
                                field.set(obj, relatedObj);
                            }
                        }
                    }
                    results.add(obj);
                }
            }
        }
        return results;
    }
}
