package orm;

import java.lang.reflect.Field;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import orm.annotations.*;

public class OrmManager {
    private Connection connection;

    public OrmManager(String dbName) {
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            this.connection = DriverManager.getConnection("jdbc:derby:" + dbName + ";create=true");
        } catch (Exception e) {
            throw new RuntimeException("Failed to connect to DB: " + e.getMessage(), e);
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public <T> void save(T obj) throws Exception {
        EntityMetaData meta = new EntityMetaData(obj.getClass());
        StringBuilder sql = new StringBuilder("INSERT INTO " + meta.getTableName() + " (");
        StringBuilder placeholders = new StringBuilder();
        List<Object> values = new ArrayList<>();

        Field idField = meta.getIdField();
        idField.setAccessible(true);
        Object idValue = idField.get(obj);
        boolean autoGenerated = false;
        if (idValue == null || (idValue instanceof Integer && ((Integer) idValue) == 0)) {
            autoGenerated = true;
        } else {
            Column idColumn = idField.getAnnotation(Column.class);
            sql.append(idColumn.name());
            placeholders.append("?");
            values.add(idValue);
        }

        for (Field field : meta.getColumns()) {
            if (field.equals(idField)) continue;
            field.setAccessible(true);
            String columnName;
            Object fieldValue;
            if (field.isAnnotationPresent(Column.class)) {
                 Column column = field.getAnnotation(Column.class);
                 columnName = column.name();
                 fieldValue = field.get(obj);
            } else if (field.isAnnotationPresent(JoinColumn.class)) {
                 JoinColumn joinColumn = field.getAnnotation(JoinColumn.class);
                 columnName = joinColumn.name();
                 Object relatedObj = field.get(obj);
                 if (relatedObj != null) {
                      // Assume the related object has a getId() method
                      fieldValue = relatedObj.getClass().getMethod("getId").invoke(relatedObj);
                 } else {
                      fieldValue = null;
                 }
            } else {
                 continue;
            }
            if (sql.toString().endsWith("(")) {
                 sql.append(columnName);
                 placeholders.append("?");
            } else {
                 sql.append(", ").append(columnName);
                 placeholders.append(", ?");
            }
            values.add(fieldValue);
        }


        // If no columns were added (e.g., auto-generated only entity), use DEFAULT VALUES syntax
        if (sql.toString().endsWith("(")) {
            sql = new StringBuilder("INSERT INTO " + meta.getTableName() + " DEFAULT VALUES");
        } else {
            sql.append(") VALUES (").append(placeholders).append(")");
        }

        if (autoGenerated) {
            try (PreparedStatement stmt = connection.prepareStatement(sql.toString(), Statement.RETURN_GENERATED_KEYS)) {
                if (!sql.toString().contains("DEFAULT VALUES")) {
                    for (int i = 0; i < values.size(); i++) {
                        stmt.setObject(i + 1, values.get(i));
                    }
                }
                stmt.executeUpdate();
                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        int generatedId = generatedKeys.getInt(1);
                        idField.set(obj, generatedId);
                    }
                }
            }
        } else {
            try (PreparedStatement stmt = connection.prepareStatement(sql.toString())) {
                for (int i = 0; i < values.size(); i++) {
                    stmt.setObject(i + 1, values.get(i));
                }
                stmt.executeUpdate();
            }
        }
    }


    public <T> T find(Class<T> clazz, Object id) throws Exception {
        EntityMetaData meta = new EntityMetaData(clazz);
        Field idField = meta.getIdField();
        Column idColumn = idField.getAnnotation(Column.class);
        String idColumnName = idColumn.name();

        String sql = "SELECT * FROM " + meta.getTableName() + " WHERE " + idColumnName + " = ?";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setObject(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    T obj = clazz.getDeclaredConstructor().newInstance();
                    idField.setAccessible(true);
                    idField.set(obj, rs.getObject(idColumn.name()));
                    for (Field field : meta.getColumns()) {
                        if (field.equals(idField)) continue;
                        field.setAccessible(true);
                        if (field.isAnnotationPresent(Column.class)) {
                             Column column = field.getAnnotation(Column.class);
                             field.set(obj, rs.getObject(column.name()));
                        } else if (field.isAnnotationPresent(JoinColumn.class)) {
                             JoinColumn joinColumn = field.getAnnotation(JoinColumn.class);
                             Object fk = rs.getObject(joinColumn.name());
                             if (fk != null) {
                                  // Load the related entity using its class and the foreign key
                                  Object relatedObj = find(field.getType(), fk);
                                  field.set(obj, relatedObj);
                             }
                        }
                    }
                    return obj;
                } else {
                    return null;
                }
            }
        }
    }

    public <T> List<T> findAll(Class<T> clazz) throws Exception {
        EntityMetaData meta = new EntityMetaData(clazz);
        List<T> results = new ArrayList<>();
        Field idField = meta.getIdField();

        String sql = "SELECT * FROM " + meta.getTableName();
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    T obj = clazz.getDeclaredConstructor().newInstance();
                    idField.setAccessible(true);
                    idField.set(obj, rs.getObject(idField.getAnnotation(Column.class).name()));
                    for (Field field : meta.getColumns()) { // ✅ UPDATED
                        if (field.equals(idField)) continue;
                        field.setAccessible(true);
                        Column column = field.getAnnotation(Column.class);
                        field.set(obj, rs.getObject(column.name())); // ✅ UPDATED
                    }
                    results.add(obj);
                }
            }
        }
        return results;
    }
}
